Выполнил задание 4.16
htmlacademy-javascript/624885-kekstagram-30 pull request #4
Opened 2023-10-17 10:53 UTC by ivnikonHA

2023-10-17 15:45 UTC, slavkapiyavka requested changes

2023-10-17 15:45 UTC, slavkapiyavka commented on js/main.js
> +function getRandomNumber(from, to) {
функция работает не совсем корректно - если from будет больше to, функция вернет undefined. нужно всегда возвращать число в диапазоне

2023-10-17 15:45 UTC, slavkapiyavka commented on js/main.js
> +const commentIds = {};
- это должен быть массив, а не объект и он должен лежать внутри getCommentId.
- сейчас же ты не сохраняешь значения в этом объекте, делая его бесполезным. после того как ты генерируешь уникальный ID, его следует добавить в этот массив.

2023-10-17 15:45 UTC, slavkapiyavka commented on js/main.js
> +  description: DESCRIPTIONS[postId],
лучше использовать getRandomArrayElement на длине массива DESCRIPTIONS, потому что если ты попытаешься создать больше 25 постов, то будет ошибка

2023-10-17 15:45 UTC, slavkapiyavka commented on js/main.js
> +for(let i = 0;i < 25;i++) {
стоит начать итерацию с 1

2023-10-18 10:00 UTC, ivnikonHA commented on js/main.js
> +for(let i = 0;i < 25;i++) {
Не понял почему? Первый элемент массива будет пустой?

2023-10-18 10:00 UTC, ivnikonHA commented on js/main.js
> +  description: DESCRIPTIONS[postId],
Не совсем понятно почему лучше использовать случайные повторяющиеся описания. Картинок у нас 25, если добавлять картинки ,то добавлять и описания. С таким же успехом мы можем использовать вместо массива DESCRIPTIONS - константу.

2023-10-18 16:02 UTC, slavkapiyavka commented on js/main.js
> +for(let i = 0;i < 25;i++) {
> Не понял почему? Первый элемент массива будет пустой?

да, в задании написано от 1 до 25, то есть стоит поправить цикл let i = 1;i <= 25;i++

2023-10-18 23:08 UTC, slavkapiyavka requested changes

2023-10-18 23:08 UTC, slavkapiyavka commented on js/main.js
> +  const commentIds = [];
хорошо что ты перенёс commentsId внутрь, но теперь вызов функции getCommentId на 85 строке генерирует новый массив commentIds на каждом вызове.
то есть идентификатор из этой функции не будет уникальным

2023-10-21 16:33 UTC, merged